modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="ends_delight"
version="1.19.2-2.1"
displayName="End's Delight"
logoFile="logo.png"
logoBlur=false
credits="GamingeckeSpace, mpustovoi, PExPE3, Roby1164, SABITRON, tankplanelaserkoala, TheLegendofSaram, unroman and many others!"
authors="FoggyHillside"
description='''
An addon mod for Farmer's Delight based around adding culinary content to the end!
'''
[[dependencies.ends_delight]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ends_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.19-1.2.4,)"
    ordering="AFTER"
    side="BOTH"